name: Build

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cache vcpkg packages
        uses: actions/cache@v5
        with:
          path: C:\vcpkg\installed
          key: vcpkg-x64-windows-static-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json') }}
          restore-keys: vcpkg-x64-windows-static-

      - name: Install dependencies via vcpkg
        run: vcpkg install --triplet x64-windows-static

      - name: Configure CMake
        run: >
          cmake -B build 
          -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake 
          -DVCPKG_TARGET_TRIPLET=x64-windows-static

      - name: Build
        run: cmake --build build --config Release

      - name: Assemble artifact
        run: |
          mkdir dist
          copy build\Release\fische.exe dist\
        shell: cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: fische-windows-x64
          path: dist/

      # - name: Upload release asset (on tag)
      #   if: startsWith(github.ref, 'refs/tags/')
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: fische-windows-bin\*
